name: Java CI - LSP4Jakarta

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build LSP4Jakarta JDT LS Extension with Maven
        working-directory: ./jakarta.jdt
        run: mvn clean install --file pom.xml
      - name: Build LSP4Jakarta Language Server with Maven
        working-directory: ./jakarta.ls
        run: mvn clean install --file pom.xml 
      - name: Build LSP4Jakarta Eclipse client plug-in with Maven
        working-directory: ./jakarta.eclipse
        run: mvn clean install --file pom.xml
          
